import type { ContentPack } from "../types";
import { buildItems } from "./build";

/**
 * FOOD FUN — everyday food a pre-K child recognises on sight.
 *
 * Chosen for glyph legibility at small sizes as much as for vocabulary: a
 * banana and an apple are unmistakable at 40 px on a phone, which is what a
 * bubble actually is.
 */
export const FOOD_FUN: ContentPack = {
  id: "food-fun",
  title: "Food Fun",
  blurb: "Snacks, fruit and things to drink.",
  glyph: "🍎",
  gradient: "from-[#ffb45c] to-[#ef6d3a]",
  items: buildItems("food-fun", [
    {
      id: "milk",
      word: "milk",
      glyph: "🥛",
      sound: "m",
      phrase: "cold milk",
      sentence: "I am drinking milk.",
      tags: ["food", "drink"],
    },
    {
      id: "muffin",
      word: "muffin",
      glyph: "🧁",
      sound: "m",
      phrase: "warm muffin",
      sentence: "I am eating a muffin.",
      tags: ["food", "treat"],
    },
    {
      id: "banana",
      word: "banana",
      glyph: "🍌",
      sound: "b",
      phrase: "yellow banana",
      sentence: "I am eating a banana.",
      color: "yellow",
      tags: ["food", "fruit"],
    },
    {
      id: "bread",
      word: "bread",
      glyph: "🍞",
      sound: "b",
      phrase: "soft bread",
      sentence: "I am eating bread.",
      color: "brown",
      tags: ["food"],
    },
    {
      id: "pizza",
      word: "pizza",
      glyph: "🍕",
      sound: "p",
      phrase: "hot pizza",
      sentence: "I am eating pizza.",
      tags: ["food", "dinner"],
    },
    {
      id: "pear",
      word: "pear",
      glyph: "🍐",
      sound: "p",
      phrase: "green pear",
      sentence: "I am eating a pear.",
      color: "green",
      tags: ["food", "fruit"],
    },
    {
      id: "soup",
      word: "soup",
      glyph: "🍲",
      sound: "s",
      phrase: "warm soup",
      sentence: "I am eating soup.",
      tags: ["food", "dinner"],
    },
    {
      id: "strawberry",
      word: "strawberry",
      glyph: "🍓",
      sound: "s",
      phrase: "red strawberry",
      sentence: "I am eating a strawberry.",
      color: "red",
      tags: ["food", "fruit"],
    },
    {
      id: "lemon",
      word: "lemon",
      glyph: "🍋",
      sound: "l",
      phrase: "sour lemon",
      sentence: "I can see a lemon.",
      color: "yellow",
      tags: ["food", "fruit"],
    },
    {
      id: "lollipop",
      word: "lollipop",
      glyph: "🍭",
      sound: "l",
      phrase: "sweet lollipop",
      sentence: "I am eating a lollipop.",
      color: "pink",
      tags: ["food", "treat"],
    },
    {
      id: "fries",
      word: "fries",
      glyph: "🍟",
      sound: "f",
      phrase: "hot fries",
      sentence: "I am eating fries.",
      tags: ["food", "dinner"],
    },
    {
      id: "fruit",
      word: "fruit",
      glyph: "🍇",
      sound: "f",
      phrase: "purple fruit",
      sentence: "I am eating fruit.",
      color: "purple",
      tags: ["food", "fruit"],
    },
    {
      id: "water",
      word: "water",
      glyph: "💧",
      sound: "w",
      phrase: "cold water",
      sentence: "I am drinking water.",
      color: "blue",
      tags: ["food", "drink"],
    },
    {
      id: "watermelon",
      word: "watermelon",
      glyph: "🍉",
      sound: "w",
      phrase: "big watermelon",
      sentence: "I am eating watermelon.",
      color: "red",
      tags: ["food", "fruit"],
    },
    {
      id: "apple",
      word: "apple",
      glyph: "🍎",
      phrase: "red apple",
      sentence: "I am eating an apple.",
      color: "red",
      tags: ["food", "fruit"],
    },
    {
      id: "egg",
      word: "egg",
      glyph: "🥚",
      phrase: "little egg",
      sentence: "I am eating an egg.",
      tags: ["food"],
    },
    {
      id: "cake",
      word: "cake",
      glyph: "🍰",
      phrase: "big cake",
      sentence: "I am eating cake.",
      tags: ["food", "treat"],
    },
    {
      id: "carrot",
      word: "carrot",
      glyph: "🥕",
      phrase: "orange carrot",
      sentence: "I am eating a carrot.",
      color: "orange",
      tags: ["food", "vegetable"],
    },
  ]),
};
