import type { ContentPack } from "../types";
import { buildItems } from "./build";

/**
 * OUTSIDE ADVENTURES — the park, the garden and the weather.
 *
 * Carries the nature sound recipes and most of the "where" language, so it
 * is the pack a game reaches for when a scene needs a place rather
 * than a thing.
 */
export const OUTSIDE_ADVENTURES: ContentPack = {
  id: "outside-adventures",
  title: "Outside Adventures",
  blurb: "The park, the garden and the weather.",
  glyph: "🌳",
  gradient: "from-[#8ee08a] to-[#3f9e6c]",
  items: buildItems("outside-adventures", [
    {
      id: "mud",
      word: "mud",
      glyph: "🟤",
      sound: "m",
      phrase: "wet mud",
      sentence: "The mud is under my boots.",
      color: "brown",
      tags: ["outside", "garden"],
    },
    {
      id: "mountain",
      word: "mountain",
      glyph: "⛰️",
      sound: "m",
      phrase: "big mountain",
      sentence: "The mountain is very high.",
      shape: "triangle",
      tags: ["outside"],
    },
    {
      id: "bush",
      word: "bush",
      glyph: "🌳",
      sound: "b",
      phrase: "green bush",
      sentence: "The bush is next to the path.",
      color: "green",
      tags: ["outside", "garden"],
    },
    {
      id: "puddle",
      word: "puddle",
      glyph: "💦",
      sound: "p",
      phrase: "big puddle",
      sentence: "I am jumping in the puddle.",
      color: "blue",
      shape: "oval",
      tags: ["outside", "rain"],
    },
    {
      id: "park",
      word: "park",
      glyph: "🛝",
      sound: "p",
      phrase: "busy park",
      sentence: "We are playing at the park.",
      tags: ["outside", "play"],
    },
    {
      id: "sun",
      word: "sun",
      glyph: "☀️",
      sound: "s",
      phrase: "hot sun",
      sentence: "The sun is shining today.",
      color: "yellow",
      shape: "circle",
      tags: ["outside", "weather"],
    },
    {
      id: "snow",
      word: "snow",
      glyph: "❄️",
      sound: "s",
      phrase: "cold snow",
      sentence: "The snow is falling down.",
      tags: ["outside", "weather"],
    },
    {
      id: "swing",
      word: "swing",
      glyph: "🎠",
      sound: "s",
      phrase: "high swing",
      sentence: "I am going high on the swing.",
      tags: ["outside", "play"],
    },
    {
      id: "leaf",
      word: "leaf",
      glyph: "🍂",
      sound: "l",
      phrase: "brown leaf",
      sentence: "The leaf is falling from the tree.",
      color: "brown",
      tags: ["outside", "garden"],
    },
    {
      id: "log",
      word: "log",
      glyph: "🪵",
      sound: "l",
      phrase: "long log",
      sentence: "The log is next to the path.",
      color: "brown",
      tags: ["outside", "forest"],
    },
    {
      id: "flower",
      word: "flower",
      glyph: "🌻",
      sound: "f",
      phrase: "yellow flower",
      sentence: "The flower is growing in the sun.",
      color: "yellow",
      tags: ["outside", "garden"],
    },
    {
      id: "field",
      word: "field",
      glyph: "🌾",
      sound: "f",
      phrase: "green field",
      sentence: "The field is full of grass.",
      color: "green",
      tags: ["outside", "farm"],
    },
    {
      id: "wind",
      word: "wind",
      glyph: "🌬️",
      sound: "w",
      phrase: "cold wind",
      sentence: "The wind is blowing my hat.",
      listen: "wind",
      tags: ["outside", "weather"],
    },
    {
      id: "water",
      word: "water",
      glyph: "🌊",
      sound: "w",
      phrase: "blue water",
      sentence: "The water is cold today.",
      color: "blue",
      tags: ["outside", "weather"],
    },
    {
      id: "rain",
      word: "rain",
      glyph: "🌧️",
      phrase: "wet rain",
      sentence: "The rain is falling on the roof.",
      listen: "rain",
      tags: ["outside", "weather"],
    },
    {
      id: "storm",
      word: "storm",
      glyph: "⛈️",
      phrase: "loud storm",
      sentence: "The storm is very loud tonight.",
      listen: "thunder",
      tags: ["outside", "weather"],
    },
    {
      id: "tree",
      word: "tree",
      glyph: "🌲",
      phrase: "tall tree",
      sentence: "The tree is next to my house.",
      color: "green",
      shape: "triangle",
      tags: ["outside", "garden"],
    },
    {
      id: "cloud",
      word: "cloud",
      glyph: "☁️",
      phrase: "white cloud",
      sentence: "The cloud is up in the sky.",
      shape: "oval",
      tags: ["outside", "weather"],
    },
  ]),
};
